[phases.setup]
nixPkgs = [
  "python311",
  "pkg-config",
  "lapack",
  "blas"
]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python server.py"




